export const timezones = [
  { value: "Etc/GMT+12", label: "Etc/GMT+12 (UTC−12:00)" },
  { value: "Etc/GMT+11", label: "Etc/GMT+11 (UTC−11:00)" },
  { value: "Pacific/Honolulu", label: "Pacific/Honolulu (UTC−10:00)" },
  { value: "America/Anchorage", label: "America/Anchorage (UTC−09:00)" },
  { value: "America/Los_Angeles", label: "America/Los_Angeles (UTC−08:00)" },
  { value: "America/Denver", label: "America/Denver (UTC−07:00)" },
  { value: "America/Chicago", label: "America/Chicago (UTC−06:00)" },
  { value: "America/New_York", label: "America/New_York (UTC−05:00)" },
  { value: "America/Caracas", label: "America/Caracas (UTC−04:00)" },
  { value: "America/Sao_Paulo", label: "America/Sao_Paulo (UTC−03:00)" },
  { value: "Atlantic/Azores", label: "Atlantic/Azores (UTC−02:00)" },
  { value: "Europe/London", label: "Europe/London (UTC+00:00)" },
  { value: "Europe/Paris", label: "Europe/Paris (UTC+01:00)" },
  { value: "Europe/Moscow", label: "Europe/Moscow (UTC+03:00)" },
  { value: "Asia/Dubai", label: "Asia/Dubai (UTC+04:00)" },
  { value: "Asia/Karachi", label: "Asia/Karachi (UTC+05:00)" },
  { value: "Asia/Kolkata", label: "Asia/Kolkata (UTC+05:30)" },
  { value: "Asia/Bangkok", label: "Asia/Bangkok (UTC+07:00)" },
  { value: "Asia/Shanghai", label: "Asia/Shanghai (UTC+08:00)" },
  { value: "Asia/Tokyo", label: "Asia/Tokyo (UTC+09:00)" },
  { value: "Australia/Sydney", label: "Australia/Sydney (UTC+10:00)" },
  { value: "Pacific/Auckland", label: "Pacific/Auckland (UTC+12:00)" }
];